package mkpmobileutils

var (
	//DEFAULT CONSTANT
	YES = "YES"
	NO  = "NO"

	TRUE_VALUE         = true
	FALSE_VALUE        = false
	EMPTY_VALUE        = ""
	ZERO_VALUE         = 0
	ZERO_VALUE_INT64   = int64(0)
	ZERO_VALUE_INT32   = int32(0)
	ZERO_VALUE_FLOAT64 = float64(0)
	ZERO_VALUE_FLOAT32 = float32(0)
	YES_VALUE          = "Y"
	NO_VALUE           = "N"

	//TIMESTAMP FORMAT
	LAYOUT_TIMESTAMP        = "2006-01-02 15:04:05"
	LAYOUT_DATE             = "2006-01-02"
	LAYOUT_TIMESTAMP_GOLANG = "2006-01-02T15:04:05Z"
	LAYOUT_DATETIME_STRING  = "20060102150405"
	LAYOUT_DATE_STRING      = "20060102"

	// DEFAULT RESPONSE CODE
	SUCCESS_CODE = "00"
	PENDING_CODE = "02"
	FAILED_CODE  = "03"

	DATA_NOT_FOUND_CODE  = "21"
	VALIDATE_ERROR_CODE  = "22"
	EXPIRED_ERROR_CODE   = "23"
	VALIDATE_ERROR_EXITS = "49"

	SYSTEM_ERROR_CODE    = "51"
	UNDEFINED_ERROR_CODE = "52"

	// DEFAULT RESPONSE MESSAGE
	SUCCESS_MESSAGE = "SUCCESS"
	PENDING_MESSAGE = "PENDING"
	FAILED_MESSAGE  = "FAILED"

	DATA_NOT_FOUND_MESSAGE       = "DATA NOT FOUND"
	VALIDATE_ERROR_MESSAGE       = "VALIDATE ERROR"
	EXPIRED_ERROR_MESSAGE        = "EXPIRED"
	VALIDATE_ERROR_EXITS_MESSAGE = "VALIDATE EXIT"

	SYSTEM_ERROR_MESSAGE    = "SYSTEM ERROR"
	UNDEFINED_ERROR_MESSAGE = "UNDEFINED ERROR"

	// CONSTANTS TRX STATUS CODE
	TRX_SUCCESS_CODE       = "00"
	TRX_PENDING_CODE       = "21"
	TRX_GAGAL_CODE         = "51"
	TRX_INQUIRY_CODE       = "66"
	TRX_INQUIRY_GAGAL_CODE = "61"
	TRX_SUSPECT_CODE       = "99"
	TRX_CANCEL_CODE        = "10"
	TRX_EXPIRED_CODE       = "999"

	// CONSTANTS TRX STATUS DESC
	TRX_SUCCESS_DESC       = "SUCCESS"
	TRX_PENDING_DESC       = "PENDING"
	TRX_GAGAL_DESC         = "FAILED"
	TRX_INQUIRY_DESC       = "INQUIRY"
	TRX_INQUIRY_GAGAL_DESC = "INQUIRY_FAILED"
	TRX_SUSPECT_DESC       = "SUSPECT"
	TRX_CANCEL_DESC        = "CANCELED"
	TRX_EXPIRED_DESC       = "EXPIRED"

	// WORKER
	TIPE_REQUEST_URL_ENCODED = "urlencoded"
	TIPE_REQUEST_JSON        = "json"

	// INTERNAL_ERROR

	// INQUIRY
	// BILLER
	// AUTH

	// PAYMENT
	// ADVICE

)
